---
title: "EPI/BIOSTAT Math and R Skills Preparatory Workshop"
author: "Jessica Williams-Nguyen and Brian Williamson"
date: "22, 25, 26 September, 2017"
output:
  html_document:
    keep_md: yes
  pdf_document: default
  word_document: default
  
---
  
  This workshop is offered by the 
[University of Washington School of Public Health](http://sph.washington.edu/).
  
Taught by

Jessica Williams-Nguyen
<br/>
  [jswn@uw.edu](mailto:jswn@uw.edu)

and

[Brian D. Williamson](http://bdwilliamson.github.io)
<br/>
  [brianw26@uw.edu](mailto:brianw26@uw.edu)

# Course Goals
Prepare participants for the UW's introductory Epidemiology and Biostatistics courses through gaining/regaining familiarity with mathematical concepts, word problems, the R programming language, and the RStudio programming environment. Specifically, we will cover:

* Core mathematical concepts (order of operations, fractions, algebra, logarithms)
* Communicating and analyzing data (graphics and word problems)
* R and RStudio basiscs, accessing R help

# Cheat Sheets

[RStudio](https://www.rstudio.com/resources/cheatsheets/).

R style guides (useful for making code easy to read):
* [Google's](https://google.github.io/styleguide/Rguide.xml).
* [Hadley Wickham's](http://adv-r.had.co.nz/Style.html).

# Course Syllabus and Lecture Materials

## Day 1, 22 September 2017, 8am-12pm

**Lecture 0: Overview and Skills for Success, Jessica and Brian, 45 min** [pdf](day_1_session_1/day_1_session_1_overview.pdf)

* Introduction to the workshop, EPI/BIOST courses
* Some skills for success in graduate school

**Lecture 1: Order of operations and negative numbers, Brian, 35 min** [pdf](day_1_session_1/day_1_session_1_order-of-ops_negatives.pdf)

* Teaser trailer: word problems
    * Example: kidney stones
    * Example: statistics in medical research
* Order of operations
* Negative numbers
* Absolute value

**Lecture 2: Fractions, Percentages, and Decimals, Jessica, 60 min** [pdf](day_1_session_1/day_1_session_1_2proportions.pdf)

* Introducing proportions
* Fractions
* Other ways to represent proportions
* Proportions and other mathematical constructs in epidemiology

**Lecture 3: Algebra, Jessica, 75 min** [pdf](day_1_session_1/day_1_session_1_3algebra_crosstab.pdf)

* Solving for an unknown quantity
* Variables
* Weighted averages
* Cross-tabulation

**Extra practice**

Khan Academy offers interactive online units for most of the topics we covered today. (It may ask for a donation, but this not required to use it.) For each unit, you can take a quiz to check if you need more practice in a particular area. If so, it will direct you to areas of the site where you can review and practice those skills.
 
* [Order of operations](https://www.khanacademy.org/math/pre-algebra/pre-algebra-arith-prop/pre-algebra-order-of-operations/e/order_of_operations_2)
* [Negative numbers](https://www.khanacademy.org/math/arithmetic/arith-review-negative-numbers)
* [Fractions](https://www.khanacademy.org/math/arithmetic/fraction-arithmetic)
* [Decimals](https://www.khanacademy.org/math/arithmetic/arith-decimals)
* [Relationship of fractions, decimals and percentages](https://www.khanacademy.org/math/cc-seventh-grade-math/cc-7th-fractions-decimals)
* [Algebra foundations (variables and substitution)](https://www.khanacademy.org/math/algebra/introduction-to-algebra)
* [Functions](https://www.khanacademy.org/math/algebra/algebra-functions)

## Day 2, 25 September 2017, 2-5:30pm

**Lecture 4: Graphs, Brian, 50 min** [pdf](day_2_session_1/day_2_session_1_graphs.pdf)

* Slope-intercept and point slope form
* Drawing graphs based on an equation for a line
* Determining the equation from a graph
* Transformations: shifting and stretching

**Lecture 5: Logarithms and Exponents, Brian, 40 min** [pdf](day_2_session_1/day_2_session_1_log.pdf)

* Why transform our data?
* Exponentiation
* Logarithms
* Example: gender bias in salaries

**Lecture 6: Word Problems, Jessica, 45 min** [pdf](day_2_session_1/day_2_session_1_6word_problems.pdf)

* Using units
* Steps for solving word problems
* Example
* Exercises

**Extra Practice**

* [Graphs](https://www.khanacademy.org/math/algebra-basics/alg-basics-graphing-lines-and-slope)
* Transforming functions:
  * [Stretching](https://www.khanacademy.org/math/algebra2/manipulating-functions#shifting-functions)
  * [Shrinking](https://www.khanacademy.org/math/algebra2/manipulating-functions#stretching-functions)
* [Logarithms and exponents](https://www.khanacademy.org/math/algebra2/exponential-and-logarithmic-functions)

## Day 3, 26 September 2017, 8-10:30am

**Lecture 7: Installing R and RStudio, Brian, 20 min (much live demo)** [pdf](day_3_session_1/day_3_session_1_install.pdf)

**Lecture 8: R and RStudio basics, Brian, 90 min (much live demo)** [pdf](day_3_session_1/day_3_session_1_basics.pdf)

* R interface
* RStudio interface
* R scripts
* Intro to R programming
    * Functions
    * Objects
    * Loading/saving data
    * Manipulating data (indexing, subsetting)
* R packages

**Lecture 9: Accessing help, Brian, 40 min (much live demo)** [pdf](day_3_session_1/day_3_session_1_help.pdf)

* Help files within R/on CRAN
* Help on the web

# Recommended Reading/Browsing

## R
* [Lecture notes on data types and data structures](2016-materials/day_3_session_1_datatypes.html) (from 2016)
* [Hadley Wickham's book](http://adv-r.had.co.nz/)

## Reproducible Research

* [Christopher Gandrud, Reproducible Research with R and Rstudio, (2015)](http://www.amazon.com/Reproducible-Research-Studio-Second-Chapman-ebook/dp/B010ACWGBI/ref=tmm_kin_title_0?_encoding=UTF8&sr=&qid=)
* [Hadley Wickham, R Packages (2015)](http://www.amazon.com/R-Packages-Hadley-Wickham-ebook/dp/B00VAYCHL0/ref=pd_sim_351_6?ie=UTF8&refRID=1E8HS30WBHRCW45SEWXM)
* [Yihui Xie, Dynamic Documents with R and knitr, (2015)](http://www.amazon.com/Dynamic-Documents-knitr-Second-Chapman-ebook/dp/B00ZBYPJEW/ref=tmm_kin_title_0?_encoding=UTF8&sr=&qid=)
* [Karl Broman's Tools for RR Course](http://kbroman.org/Tools4RR/)